config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :tasks
  root 'pages#home'
  get 'signup', to: 'users#new', as: 'sign-up'
  resources :users, except: [:new]
  get 'signin', to: 'sessions#new', as: 'sign-in'
  post 'signin', to: 'sessions#create'
  delete 'signout', to: 'sessions#destroy', as: 'sign-out'
end 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    validates :cname, presence: true, length: { minimum: 3, maximum: 30 }
    validates_uniqueness_of :cname
    
    has_many :task_categories
    has_many :tasks, through: :task_categories
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :user
    has_many :task_categories
    has_many :categories, through: :task_categories

    validates :title, presence: true, length: { minimum: 4, maximum: 100 }
    validates :description, presence: true, length: { minimum: 6, maximum: 300 }
end

app/models/task_category.rb
class TaskCategory < ApplicationRecord
    belongs_to :task
    belongs_to :category
  end

app/models/user.rb
class User < ApplicationRecord
    has_many :tasks, dependent: :destroy
    validates :name, presence: true, 
                        uniqueness: { case_sensitive: false }, 
                        length: { minimum: 3, maximum: 25 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, 
                        uniqueness: { case_sensitive: false }, 
                        length: { maximum: 105 },
                        format: { with: VALID_EMAIL_REGEX }
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?

    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
  
    def logged_in?
      !!current_user
    end
  
    def require_user
      if !logged_in?
        flash[:alert] = "You must be logged in to perform that action"
        redirect_to sign_in_path
      end
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def show
    redirect_to categories_path
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = 'Category was successfully created.'
      redirect_to @category
    else
      render 'new'
    end
  end

  def update
    if @category.update(category_params)
      flash[:notice] = 'Category was successfully updated.'
      redirect_to @category
    else
      render 'edit'
    end
  end

  def destroy
    @category.destroy
    flash[:notice] = 'Category was successfully destroyed.'
    redirect_to categories_url
  end

  private
   
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:cname)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def home
        redirect_to tasks_path if logged_in?
    end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
     redirect_to tasks_path if logged_in?
    end

    def create
        user = User.find_by(email: params[:session][:email])
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:notice] = "Sign In successfully"
            redirect_to tasks_path
        else
            flash.now[:alert] = "There was something wrong with your Sign In details"
            render 'new'
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:notice] = "Sign Out successfully"
        redirect_to root_path
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :require_user
  def index
    @tasks = Task.where(tdate: Date.today).where(user: current_user)
  end
  
  def show
  end

  def new
    @task = Task.new
  end

  def edit
  end

  def create
    @task = Task.new(task_params)
    @task.user = current_user
    if @task.save
      flash[:notice] = 'Task was successfully created.'
      redirect_to @task
    else
      render "new"
    end
  end

  def update
    if @task.update(task_params)
      flash[:notice] = 'Task was successfully updated.'
      redirect_to @task
    else
      render "edit"
    end
  end

  def destroy
    @task.destroy
    flash[:notice] = 'Task was successfully destroyed.'
    redirect_to tasks_url 
  end

  private
    def set_task
      @task = Task.find(params[:id])
    end

    def task_params
      params.require(:task).permit(:title, :description, :tdate, category_ids: [])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  
  def show
    @tasks = @user.tasks
  end

  def new
    @user = User.new
  end

  def create

    @user = User.new(user_params)
      if @user.save
          flash[:notice] = "Welcome #{@user.name}, you have successfully signed up"
          redirect_to sign_in_path
      else
          render "new"
    end
  end

    
  private
  def user_params
      params.require(:user).permit(:name, :email, :password)
  end

  def set_user
      @user = User.find(params[:id])
  end
end 

app/helpers/application_helper.rb
module ApplicationHelper

    def gravatar_for(user, options = { size: 80})
        email_address = user.email
        hash = Digest::MD5.hexdigest(email_address)
        size = options[:size]
        gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar rounded shadow mx-auto d-block")
    end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/_category.html.erb
<%= link_to category.cname, categories_path, class: "badge badge-pill badge-info mr-1" %>

app/views/categories/_form.html.erb
<div class="container bg-secondary rounded px-4 py-2 shadow-lg">
  <div class="form-wrapper">
    <%= form_with(model: @category, local: true) do |f| %>

    <%= render 'shared/errors', obj: @category%>

      <%= f.label :cname,'Category Name', class: "text-white font-weight-bold" %>
      <%= f.text_field :cname, class: "form-control border", placeholder: "Enter category name" %>
      
      <div class='text-center mt-3'>
        <%= f.submit(class: "btn btn-info my-2") %>
        <br>
        <%= link_to 'Back', categories_path, class: "text-info" %>
      </div>
    <% end %>
  </div>
</div> 

app/views/categories/edit.html.erb
<h1 class="text-center mt-4">Edit Category</h1>
<%= render 'form' %>

app/views/categories/index.html.erb
<div class='d-flex flex-column align-items-center my-3 w-75 shadow-lg bg-dark mx-auto rounded categories_bg {
  animation: fade-from-center 1.5s ease-in forwards;
}'>
  <h1 class='text-center mt-4 px-2 text-white text-uppercase font-weight-bold border-bottom  border-top border-light rounded'>Categories</h1>
   
   <div class="card text-center w-75 mb-4 d-flex flex-row bg-dark border-0">
  <% @categories.each do |category| %>
    <div class='border my-3 rounded w-25 mx-2 px-2 bg-secondary cat_hover'>
      <div class='card-body'>
        <h4 class="card-title text-white text-uppercase"><%= category.cname %></h4>
        <p class="card-text text-white"><%= pluralize(category.tasks.count, "task") %></p>
        <small>Created <%= time_ago_in_words( category.created_at) %> ago</small>
        <% if logged_in? %>
        <div>
        <%= link_to '', edit_category_path(category), class: 'btn btn-sm btn-info bi bi-pencil-fill' %> 
        <%= link_to '', category, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger bi bi-trash-fill' %>
        </div>
        <% end %>
     </div>
    </div>
    <% end %>
  </div>
     <% if logged_in? %>
      <%= link_to 'New Category', new_category_path , class: 'btn btn-outline-secondary mb-3 text-white' %>
    <% end %>
</div>

app/views/categories/new.html.erb
<h1 class="text-center mt-4">New Category</h1>
<%= render 'form' %>

app/views/layouts/_footer.html.erb
<footer class="bg-secondary text-white text-center text-lg-start">
  <div class='py-2'>
    <div id='Social pt-3 '>
      <a href="https://www.facebook.com/CyrilSalas.14/" target="_blank" class='mx-1 bi bi-facebook text-white social'></a>
      <a href="https://www.instagram.com/jcsalas14/" target="_blank" class='mx-1 bi bi-instagram text-white social'></a>
      <a href="https://twitter.com/CyrilJomari" target="_blank" class='mx-1 bi bi-twitter text-white social'></a>
      <a href="https://www.linkedin.com/in/jomari-cyril-salas-a391161a4/" target="_blank" class='mx-1 bi bi-linkedin text-white social'></a>
    </div>
    <div class="text-center text-white" >
      © 2021 Copyright:
      <a class="text-white" href="https://github.com/jcsalasdev">jcsalasdev</a>
    </div>
  </div>
</footer>

app/views/layouts/_message.html.erb
<div class='d-flex justify-content-center'>
    <% flash.each do |name, msg| %>
        <div class="mt-2 mb-0 alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
            <%= msg %>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
    <% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark bg.gradient">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active pt-1">
        <%= link_to "TM", root_path, class: "navbar-brand text-white font-weight-bold border px-1 py-0 rounded" %>
      </li>
      <% if logged_in? %>
      <li class="nav-item">
        <%= link_to "Task", tasks_path, class: "nav-link text-white" %>
      </li> 

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Categories
        </a>
        <div class="dropdown-menu bg_opacity" aria-labelledby="navbarDropdown">
          <%= link_to "View categories", categories_path, class: "dropdown-item" %>
          
          <%= link_to "New category", new_category_path, class: "dropdown-item" %>
        <% end %>  
        </div>
      </li>
    </ul>

    <% if logged_in? %>
    <div class="navbar-nav ml-auto">
      <div class='text-white nav-item'>
          <%= link_to "Profile", user_path(current_user), class: "text-white nav-link" %>
      </div>
      
      <span class="text-white nav-link">|</span>

      <div class='text-white nav-item'>
          <%= link_to "Sign out",sign_out_path, class: "text-white nav-link", method: :delete %>
      </div>
      <% else %>
      <div class='text-white nav-item'>
          <%= link_to "Sign In", sign_in_path, class: "text-white nav-link" %>
      </div>
      <span class="text-white nav-link">|</span>
      <div class='text-white nav-item'>
          <%= link_to "Sign Up", sign_up_path, class: "text-white nav-link" %>
      </div>
    </div>
    <% end%>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManagerApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
 
    <%= render 'layouts/navbar' %>
    
    <div class='container-custom'>
      <%= render 'layouts/message' %>
      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>

  </body>
</html>

app/views/pages/home.html.erb
<div class='d-flex justify-content-center mt-5'>
  <div class="w-75 text-center card shadow-1-strong brand_bg"
    style="background-image: url('https://wallpaperaccess.com/full/2040033.jpg'); 
    background-repeat: none; background-position: center;  background-size: cover;"id='card-wrapper'>
      <h2 class="card-title rounded font-weight-bolder text-white myp w-50 mx-auto mt-4">Task Manager</h2>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h2 class='alert-heading'><%= pluralize(obj.errors.count, "error")%></h2>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/tasks/_form.html.erb
<div class="container bg-secondary rounded px-4 py-2 shadow-lg">
  <div class="form-wrapper">
    <%= form_with(model: @task, class: "form-group", local: true) do |f| %>
      <%= render 'shared/errors', obj: @task%>
        <%= f.label :title, class: "text-white font-weight-bold" %>
        <%= f.text_field :title, class: "form-control", placeholder: "Enter the title" %>
        
        <%= f.label :description, class: "text-white font-weight-bold pt-2" %>
        <%= f.text_area :description, class: "form-control", placeholder: "type here" %>

        <%= f.label :category,'Categories', class: "text-white font-weight-bold pt-2" %>
        <%= f.collection_select(:category_ids, Category.all, :id, :cname,
          {prompt: "Select categories here (can be empty):"}, { multiple: true, size: 3, class: "custom-select shadow rounded" }) %>
      
        <%= f.label :tdate, 'Start Date', class: "text-white font-weight-bold pt-2" %>
        <%= f.date_field :tdate, class:'form-control' %>
   
        <div class='text-center mt-3'>
        <%= f.submit(class: "btn btn-info") %>
        <br>
        <%= link_to "back to task", tasks_path, class: "text-info" %>
        </div>
    <% end %>
  </div> 
</div>

app/views/tasks/_tasks.html.erb
<div class='d-flex flex-column  align-items-center my-3 '>
  <div class="card text-center w-50 shadow-lg bg-dark my_task">
    <h1 class='mt-2 mb-0'><%= link_to '', tasks_path , class: 'text-center text-white text-uppercase font-weight-bold bi bi-badge-tm-fill' %></h1>
    <%= link_to 'New Task', new_task_path , class: 'btn btn-dark w-25 mx-auto' %>
 
    <% @tasks.each do |task| %>
      <div class='border-top border-bottom my-3 rounded w-75 mx-auto'>

        <div class="card-header bg-secondary text-white text-uppercase">
        <%= link_to task.user.name, user_path(current_user), class: "text-white" %>
        </div>
        
        <div class="card-body bg-white">
          <h4 class="card-title mb-0"><%= task.title %></h4>
          <%= render task.categories if task.categories.any? %>
          <p class="card-text mt-2"><%= task.description %></p>
          <%= link_to '', task , class: 'btn btn-sm btn-primary bi bi-eye-fill' %>
          <%= link_to '', edit_task_path(task), class: 'btn btn-sm btn-info bi bi-pencil-fill' %>
          <%= link_to '', task, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger bi bi-trash-fill' %>
        </div>
        
        <div class="card-footer text-white bg-secondary">
          <small>Created <%= time_ago_in_words(task.created_at) %> ago,
            Updated <%= time_ago_in_words(task.updated_at) %> ago</small>
        </div>

      </div>
    <% end %>
  </div>
</div>

app/views/tasks/edit.html.erb
<h3 class='text-center mt-3'>Editing Task</h3>
<%= render 'form' %>

app/views/tasks/index.html.erb
<h2 class='p-2 mt-2 text-center'>Your Task for Today</h2>
<%= render 'tasks' %>

app/views/tasks/new.html.erb
<h1 class='text-center'>New Task</h1>
<%= render 'form' %>

app/views/tasks/show.html.erb
<div class='d-flex flex-column align-items-center mt-4'>
  <div class="card text-center w-75  rounded-1 shadow-lg">

    <div class="card-header text-uppercase font-weight-bold ">
       <i class="bi bi-person-circle"></i>
        <%= @task.user.name if logged_in?%>
    </div>
    <div class="card-body">
      <h5 class="card-title mb-0"><%= @task.title %></h5>
      <%= render @task.categories if @task.categories.any? %>
      <p class="card-text mt-2"><%= @task.description %></p>
      <% if logged_in? && (@task.user == current_user) %>
      <%= link_to "Edit", edit_task_path(@task), class: "btn btn-outline-info" %>
      <%= link_to "Delete", task_path(@task), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
      <% end %>
    </div>
    
    <div class="card-footer text-muted">
      <small>Created <%= time_ago_in_words(@task.created_at) %> ago</small>
      <br>
      <%= link_to "back", tasks_path, class: "text-secondary " %>
    </div>
  </div>  
</div>

app/views/users/_form.html.erb
<div class="container bg-secondary w-50 rounded px-5 py-3 shadow-lg">
<div class="form-wrapper">
    <%= form_with(model: @user, class: "form-group", local: true) do |f| %>
      <%= render 'shared/errors', obj: @user%>
        <%= f.label :name, class: "text-white font-weight-bold" %>
        <%= f.text_field :name, class: "form-control border", placeholder: "Enter your name" %>
       
        <%= f.label :email, class: "text-white font-weight-bold pt-2" %>
        <%= f.email_field :email, class: "form-control", placeholder: "Enter your email address" %>

        <%= f.label :password, class: "text-white font-weight-bold pt-2" %>
        <%= f.password_field :password, class: "form-control", placeholder: "Type a password" %>

        <div class='text-center mt-3'>
         <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-secondary btn-outline-dark text-white") %>
        </div>
    <% end %>

  </div>
</div> 

app/views/users/edit.html.erb
<h1 class="text-center mt-4">Edit your profile</h1>
<%= render 'form' %>

app/views/users/new.html.erb
<h1 class="text-center mt-4 font-weight-bold">Sign up here!</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<div class='card text-uppercase text-center w-50 mx-auto mt-3 u_card'>
    <div class='mt-3'><%= gravatar_for @user, size: 150 %></div>
    <h3 class='mt-1 font-weight-bold'><%= @user.name %></h3>
</div>

<%= render 'tasks/tasks' %>